[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "coffeeshop-python-course"
version = "0.1.0"
description = "Coffee shop ordering service on Python"
requires-python = ">=3.11"
